name       : haskell-pem
version    : 0.2.4
release    : 3
source     :
    - https://hackage.haskell.org/package/pem-0.2.4/pem-0.2.4.tar.gz : 770c4c1b9cd24b3db7f511f8a48404a0d098999e28573c3743a8a296bb96f8d4
license    : BSD-3-Clause
component  : programming.haskell
summary    : Privacy Enhanced Mail (PEM) format reader and writer.
description: |
    Privacy Enhanced Mail (PEM) format reader and writer.
builddeps  :
    - haskell-cabal-install
    - haskell-memory-devel
rundeps    :
    - devel:
        - haskell-memory-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
