name       : haskell-pem
version    : 0.2.2
release    : 1
source     :
    - http://hackage.haskell.org/package/pem-0.2.2/pem-0.2.2.tar.gz : 372808c76c6d860aedb4e30171cb4ee9f6154d9f68e3f2310f820bf174995a98
license    : BSD-3-Clause
component  : programming.haskell
summary    : Privacy Enhanced Mail (PEM) format reader and writer.
description: |
    Privacy Enhanced Mail (PEM) format reader and writer.
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
